### ISSUE TITLE
Release the new version on crates.io?

### ISSUE THREAD

**Issue by astrojhgu** [kaikalii/cargo-stabilize#2]
Hi, could you please consider to release the newly updated version (https://github.com/kaikalii/cargo-stabilize/commit/c54b8769d390e5ac39ab2c7e3017e709518b060b) on [crates.io](https://crates.io)?

So that the users can install it with `cargo install`.

**Comment by kaikalii** [comment]
[Done](https://crates.io/crates/cargo-stabilize).
